from helpers import secrets, socket

APP_NAME = "flaskblog"  # NAME OF THE FLASK APP.
APP_ROOT_PATH = "."  # THE PATH TO THE ROOT OF THE APP FILES.
APP_HOST = socket.gethostbyname(
    socket.gethostname()
)  # FLASK APP'S HOST (OR USE "localhost")
APP_PORT = 5000  # FLASK APP'S PORT.
DEBUG_MODE = True  # TURN ON/OFF FLASK DEBUG MODE.
TAILWIND_UI = False  # SELECT TAILWIND-UI/STANDARD-UI.
LOG_IN = True  # TURN ON/OFF USER LOG IN UP.
REGISTRATION = True  # TURN ON/OFF USER SIGN UP.
LOG_FILE_ROOT = "log.log"  # ROOT OF THE LOG FILE FROM WHERE MESSAGES ARE PRINTED FROM THE MESSAGE MODULE.
DB_FOLDER_ROOT = "db"  # ROOT OF THE DATABASE FOLDER WHERE .db FILES ARE LOCATED.
DB_USERS_ROOT = DB_FOLDER_ROOT + "/users.db"  # ROOT OF THE USERS DATABASE.
DB_POSTS_ROOT = DB_FOLDER_ROOT + "/posts.db"  # ROOT OF THE POSTS DATABASE.
DB_COMMENTS_ROOT = DB_FOLDER_ROOT + "/comments.db"  # ROOT OF THE COMMENTS DATABASE.
APP_SECRET_KEY = secrets.token_urlsafe(32)  # FLASK APP'S SECRET KEY.
SESSION_PERMANENT = True  # FLASK APP'S SESSIONS.
