name: Deploy Website

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to SSH Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script:
          # Navigate to the directory where the website files will be deployed
          mkdir -p noisedive  # make server folder if it does not already exist
          cd noisedive

          # Remove any existing files in the directory
          rm -rf *

          # Create a tar.gz archive of the website files from the repository
          tar -czf site.tar.gz -C ${{ github.workspace }} .

          # Extract the website files to the current directory
          tar -xzf site.tar.gz

          # Remove the archive file
          rm site.tar.gz
      env:
        TAR_OPTIONS: --directory=public  # Change this if your site is in a different directory

    - name: Copy files to server
      run: tar -czf - . | ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cat > noisedive/site.tar.gz && tar -xzf noisedive/site.tar.gz -C noisedive && rm noisedive/site.tar.gz"
